(function(){
  'use strict';

  const LANGS={en:{locale:'en-ZA',speech:'en-ZA'},zu:{locale:'zu-ZA',speech:'zu-ZA'},af:{locale:'af-ZA',speech:'af-ZA'}};
  const zu={
    'Language':'Ulimi','Skip to assessment':'Yeqela ekuhloleni','ENERGY SNAPSHOT':'ISIFINYEZO SAMANDLA','Save progress':'Londoloza ukuqhubeka','Saved ✓':'Kulondoloziwe ✓','Start again':'Qala futhi','Need help?':'Udinga usizo?',
    'COMMERCIAL · INDUSTRIAL · AGRICULTURAL':'EZOHWEBO · EZEZIMBONI · EZEZOLIMO','Your energy infrastructure should protect your business.':'Ingqalasizinda yakho yamandla kufanele ivikele ibhizinisi lakho.','Build a clear first view of your energy costs, funding options and next best step. No technical knowledge required.':'Thola umbono ocacile wokuqala wezindleko zamandla, izindlela zokuxhasa kanye nesinyathelo esilandelayo. Awudingi ulwazi lobuchwepheshe.','✓ About 3 minutes':'✓ Cishe imizuzu emi-3','✓ No obligation':'✓ Akuphoqelekile','✓ Assumptions shown':'✓ Izilinganiso ziyaboniswa','✓ Your data stays private':'✓ Idatha yakho ihlala iyimfihlo',
    'Guide me':'Ngiqondise','Simple multiple-choice questions':'Imibuzo elula ongakhetha kuyo','Recommended':'Kunconyiwe','Upload my bill':'Layisha ibhili yami','We will pre-fill what we can':'Sizogcwalisa esingakwazi','I know my numbers':'Ngiyazazi izinombolo zami','Open the advanced assessment':'Vula ukuhlola okuningiliziwe','🎙 Or tell us about your site in your own words':'🎙 Noma sichazele ngesiza sakho ngamazwi akho','Describe your electricity problem, equipment and priorities':'Chaza inkinga kagesi, imishini kanye nezinto ezibalulekile','Start voice capture':'Qala ukuqopha izwi','Listening… tap to stop':'Ngilalele… chofoza ukuze ume','Use these notes':'Sebenzisa la manothi',
    'Energy':'Amandla','Site':'Isiza','Solution':'Isixazululo','Finance':'Ezezimali','Snapshot':'Isifinyezo','Guided mode':'Indlela eqondisiwe','Advanced mode':'Indlela eningiliziwe','Advanced':'Okuningiliziwe','We will keep this simple and make transparent assumptions.':'Sizokugcina kulula futhi siveze zonke izilinganiso.','Fine-tune technical and financial assumptions.':'Lungisa izilinganiso zobuchwepheshe nezezimali.',
    'Let’s understand your energy spend':'Ake siqonde izindleko zakho zamandla','Use the number you know. You can skip anything else.':'Sebenzisa inombolo oyaziyo. Okunye ungakweqa.','I know my monthly bill':'Ngiyazi ibhili yami yenyanga','I know my monthly kWh':'Ngiyazi i-kWh yami yenyanga','Upload a bill':'Layisha ibhili','Average monthly bill':'Ibhili emaphakathi yenyanga','including VAT':'kufaka i-VAT','Average monthly usage':'Ukusetshenziswa okumaphakathi ngenyanga','How much billing history do you have?':'Unomlando wamabhili wesikhathi esingakanani?','One recent bill':'Ibhili eyodwa yakamuva','About 3 months':'Cishe izinyanga ezi-3','About 6 months':'Cishe izinyanga ezi-6','12 months or more':'Izinyanga ezi-12 noma ngaphezulu','Drop bills or meter data here':'Beka amabhili noma idatha yemitha lapha','PDF, photo, CSV or spreadsheet':'PDF, isithombe, CSV noma isipredishithi','What kind of operation is this?':'Lolu hlobo luni lwebhizinisi?','Farm / Agriculture':'Ipulazi / Ezolimo','Factory / Industrial':'Ifektri / Izimboni','Commercial / Retail':'Ezohwebo / Izitolo','Hospitality':'Izivakashi','Mining / Quarry':'Izimayini / Inkwali','Something else':'Okunye','Advanced electricity details':'Imininingwane kagesi eningiliziwe','Blended tariff':'Intengo kagesi ehlanganisiwe','Recorded peak demand':'Isidingo esiphezulu esirekhodiwe','Demand charge':'Inkokhelo yesidingo','Continue to site →':'Qhubeka ngesiza →',
    'Tell us about your site':'Sitshele ngesiza sakho','We use location and operating patterns to tighten the estimate.':'Sisebenzisa indawo nendlela yokusebenza ukwenza isilinganiso sibe ngcono.','Where is the site?':'Sikuphi isiza?','Search':'Sesha','or':'noma','◎ Use my current location':'◎ Sebenzisa indawo engikuyo','You can also choose a province below.':'Ungakhetha nesifundazwe ngezansi.','Province':'Isifundazwe','Choose province':'Khetha isifundazwe','Electricity supply':'Umhlinzeki kagesi','Eskom direct':'I-Eskom ngqo','Municipality':'Umasipala','Private / landlord':'Ozimele / umnikazi','Not sure':'Angiqiniseki','When do you use most electricity?':'Uwusebenzisa nini kakhulu ugesi?','Mostly daytime':'Ikakhulu emini','More than 60% while the sun is up':'Ngaphezu kuka-60% ngesikhathi selanga','Day and night':'Emini nasebusuku','A fairly even operating pattern':'Ukusebenza okusabalale ngokulinganayo','Mostly at night':'Ikakhulu ebusuku','Less than 30% during daytime':'Ngaphansi kuka-30% emini','What do you want to power?':'Yini ofuna ukuyinika amandla?','Choose everything that applies':'Khetha konke okusebenzayo','＋ Add custom equipment':'＋ Engeza umshini wakho','Nothing selected yet. We can estimate from your bill if you prefer.':'Akukakhethwa lutho. Singalinganisa sisebenzisa ibhili yakho.','Advanced site details':'Imininingwane yesiza eningiliziwe','Usable roof area':'Indawo yophahla engasetshenziswa','Usable ground area':'Indawo yomhlaba engasetshenziswa','Planned load growth':'Ukukhula kokusetshenziswa okuhleliwe','← Back':'← Emuva','Build my options →':'Yakha izinketho zami →',
    'Build the right energy strategy':'Yakha isu elifanele lamandla','Start with the outcome you need. Add or remove options at any time.':'Qala ngomphumela owudingayo. Engeza noma susa izinketho noma nini.','What matters most right now?':'Yini ebaluleke kakhulu manje?','Protect cash flow':'Vikela ukuhamba kwemali','Low or no upfront capital':'Imali encane noma engekho ekuqaleni','Own the system':'Yiba ngumnikazi wohlelo','Build a long-term asset':'Yakha impahla yesikhathi eside','Fastest return':'Inzuzo esheshayo','Maximise financial benefit':'Khulisa inzuzo yezezimali','How much continuity do you need?':'Udinga ukuqhubeka kwamandla okungakanani?','Cost saving':'Ukonga izindleko','No battery required':'Akudingeki ibhethri','Critical loads':'Imishini ebalulekile','Keep essentials operating':'Gcina okubalulekile kusebenza','Full-site resilience':'Ukuvikeleka kwesiza sonke','Extended operational continuity':'Ukuqhubeka kokusebenza isikhathi eside','Optional upgrades':'Izithuthukisi ongazikhetha','See the impact instantly':'Bona umthelela ngokushesha','Battery storage':'Ukugcinwa kwebhethri','Generator integration':'Ukuhlanganiswa kwejeneretha','Energy management':'Ukuphathwa kwamandla','Power-factor correction':'Ukulungisa i-power factor','Solar carports':'Ama-carport elanga','Ground-mount array':'Amaphaneli abekwe emhlabathini','EV charging ready':'Ilungele ukushaja i-EV','Export control':'Ukulawula ukuthumela kugridi','Roof reinforcement allowance':'Isabelo sokuqinisa uphahla','Extended warranty':'Iwaranti enwetshiwe','Grid application support':'Usizo lwesicelo segridi','Performance & O&M plan':'Uhlelo lokusebenza nokunakekela','Advanced operating details':'Imininingwane yokusebenza eningiliziwe','Monthly diesel spend':'Izindleko zikadizili ngenyanga','Typical outage duration':'Isikhathi esivamile sokuphela kukagesi','Critical portion of load':'Ingxenye ebalulekile yokusetshenziswa','Performance ratio':'Isilinganiso sokusebenza','Annual PV degradation':'Ukwehla kwe-PV ngonyaka','Existing generator':'Ijeneretha ekhona','None':'Akukho','Manual generator':'Ijeneretha yezandla','Automatic generator / ATS':'Ijeneretha ezenzakalelayo / ATS','Compare finance →':'Qhathanisa izimali →',
    'Compare ways to fund it':'Qhathanisa izindlela zokuyixhasa','See the estimated cash impact—not just the system price.':'Bona umthelela wemali olinganisiwe—hhayi intengo yohlelo kuphela.','Indicative project':'Iphrojekthi elinganisiwe','Year-one benefit':'Inzuzo yonyaka wokuqala','Recommended route':'Indlela enconyiwe','Outright purchase':'Ukuthenga ngokuphelele','Own from day one':'Yiba ngumnikazi kusukela ngosuku lokuqala','Bank finance':'Imali yasebhange','Deposit plus fixed loan':'Idiphozithi kanye nemalimboleko','Rent-to-own':'Qasha uze ube ngumnikazi','No or low upfront capital':'Imali encane noma engekho ekuqaleni','Energy services / PPA':'Izinsizakalo zamandla / PPA','Pay for delivered energy':'Khokhela amandla alethwayo','Adjust finance assumptions':'Lungisa izilinganiso zezimali','Bank interest':'Inzalo yasebhange','Loan term':'Isikhathi semalimboleko','Deposit':'Idiphozithi','PPA escalation':'Ukukhuphuka kwe-PPA','Grid escalation':'Ukukhuphuka kwegridi','Discount rate':'Izinga lesaphulelo','PPA starting discount':'Isaphulelo sokuqala se-PPA','PPA starting tariff':'Intengo yokuqala ye-PPA','Analysis period':'Isikhathi sokuhlaziya','Indicative company tax rate':'Isilinganiso sentela yenkampani','View my snapshot →':'Bona isifinyezo sami →',
    'YOUR PRE-FEASIBILITY SNAPSHOT':'ISIFINYEZO SAKHO SOKUHLOLA KOKUQALA','A clearer energy path starts here.':'Indlela ecacile yamandla iqala lapha.','data confidence':'ukuthembeka kwedatha','RECOMMENDED FIRST ROUTE':'INDLELA YOKUQALA ENCONYIWE','20-YEAR CAPITAL DECISION':'ISINQUMO SEMALI SEMINYAKA ENGAMA-20','What each route could cost':'Izindleko ezingaba khona zendlela ngayinye','Base':'Isisekelo','Conservative':'Okuqaphile','Upside':'Okuhle kakhulu','ENERGY MATCH':'UKUHAMBISANA KWAMANDLA','Typical operating day':'Usuku oluvamile lokusebenza','SOLUTION':'ISIXAZULULO','Proposed first configuration':'Uhlelo lokuqala oluhlongozwayo','MONTHLY ENERGY':'AMANDLA ENYANGA','Consumption and solar generation through the year':'Ukusetshenziswa nokukhiqizwa kwelanga unyaka wonke','YEAR-ONE CASH FLOW':'UKUHAMBA KWEMALI KONYAKA WOKUQALA','Where the value comes from':'Lapho inzuzo ivela khona','ENERGY FLOW':'UKUHAMBA KWAMANDLA','How energy moves through the site':'Indlela amandla ahamba ngayo esizeni','SENSITIVITY':'UKUZWELEKA','How tariff and production changes affect value':'Ukushintsha kwentengo nokukhiqiza kuthinta kanjani inzuzo','FINANCE COMPARISON':'UKUQHATHANISA IZIMALI','Decision table':'Ithebula lesinqumo','READINESS':'UKULUNGELA','What we know':'Esikwaziyo','NEXT REVIEW':'UKUBUYEKEZA OKULANDELAYO','What could change this result':'Okungashintsha lo mphumela','Anything Chariot should know?':'Kukhona okufanele uChariot akwazi?','NEXT STEP':'ISINYATHELO ESILANDELAYO','Turn this estimate into an investment-ready assessment.':'Guqula lesi silinganiso sibe ukuhlola okulungele ukutshalwa kwezimali.','Schedule an energy review →':'Hlela umhlangano wamandla →','Share with Chariot on WhatsApp':'Yabelana noChariot ku-WhatsApp','Send by email':'Thumela nge-imeyili','Download / print report':'Landa / phrinta umbiko','← Review assumptions':'← Buyekeza izilinganiso','Refine my assessment':'Lungisa ukuhlola kwami',
    'LIVE INDICATIVE VIEW':'UMBONO OBUKHOMA OLINGANISIWE','Your energy opportunity':'Ithuba lakho lamandla','System range':'Ububanzi bohlelo','Estimated capex':'Izindleko ezilinganisiwe','Cash-flow route':'Indlela yokuhamba kwemali','20-YEAR COST OUTLOOK':'UMBONO WEZINDLEKO WEMINYAKA ENGAMA-20','Now':'Manje','Data confidence':'Ukuthembeka kwedatha','Starting':'Ukuqala','Add your monthly bill to begin.':'Engeza ibhili yakho yenyanga ukuze uqale.','supplied':'kunikeziwe','Assumptions visible':'Izilinganiso ziyabonakala','WE’RE HERE TO HELP':'SILAPHA UKUSIZA','You do not need to know the technical answers.':'Akudingeki wazi izimpendulo zobuchwepheshe.','Open WhatsApp':'Vula i-WhatsApp','BOOK AN ENERGY REVIEW':'HLELA UMHLANGANO WAMANDLA','Choose a convenient starting point.':'Khetha isikhathi esikahle sokuqala.','Your name':'Igama lakho','Full name':'Igama eliphelele','Company':'Inkampani','Company or site':'Inkampani noma isiza','Phone or email':'Ucingo noma i-imeyili','How should we reach you?':'Singakuthinta kanjani?','Preferred time':'Isikhathi osithandayo','Weekday morning':'Ekuseni phakathi nesonto','Weekday afternoon':'Ntambama phakathi nesonto','As soon as possible':'Ngokushesha okukhulu','Send meeting request →':'Thumela isicelo somhlangano →','Monthly bill':'Ibhili yenyanga','Indicative solar':'Amandla elanga alinganisiwe','Battery allowance':'Isabelo sebhethri','Not included':'Akufakiwe','Indicative capex':'Izindleko zemali ezilinganisiwe','Recommended first route':'Indlela yokuqala enconyiwe','Client notes':'Amanothi eklayenti','Not specified':'Akucacisiwe','Location to confirm':'Indawo izoqinisekiswa','None supplied':'Akukho okunikeziwe','Please add your name and phone or email.':'Sicela ufake igama lakho kanye nocingo noma i-imeyili.','Chariot Energy Review Request':'Isicelo Somhlangano Wamandla we-Chariot','Name':'Igama','Company/site':'Inkampani/isiza','Not supplied':'Akukunikeziwe','Contact':'Imininingwane yokuxhumana','Clear this assessment and start again?':'Sula lokhu kuhlola bese uqala futhi?','Indicative pre-feasibility only. Please contact me to validate the assessment.':'Ukuhlola kokuqala kuphela. Sicela ungithinte ukuze kuqinisekiswe imiphumela.'
  };

  const af={
    'Language':'Taal','Skip to assessment':'Gaan na assessering','ENERGY SNAPSHOT':'ENERGIE-OORSIG','Save progress':'Stoor vordering','Saved ✓':'Gestoor ✓','Start again':'Begin weer','Need help?':'Hulp nodig?',
    'COMMERCIAL · INDUSTRIAL · AGRICULTURAL':'KOMMERSIEEL · INDUSTRIEEL · LANDBOU','Your energy infrastructure should protect your business.':'Jou energie-infrastruktuur behoort jou besigheid te beskerm.','Build a clear first view of your energy costs, funding options and next best step. No technical knowledge required.':'Kry ’n duidelike eerste oorsig van jou energiekoste, finansieringsopsies en beste volgende stap. Geen tegniese kennis nodig nie.','✓ About 3 minutes':'✓ Ongeveer 3 minute','✓ No obligation':'✓ Geen verpligting','✓ Assumptions shown':'✓ Aannames word gewys','✓ Your data stays private':'✓ Jou data bly privaat',
    'Guide me':'Lei my','Simple multiple-choice questions':'Eenvoudige meervoudigekeusevrae','Recommended':'Aanbeveel','Upload my bill':'Laai my rekening op','We will pre-fill what we can':'Ons vul vooraf in wat ons kan','I know my numbers':'Ek ken my syfers','Open the advanced assessment':'Open die gevorderde assessering','🎙 Or tell us about your site in your own words':'🎙 Of vertel ons van jou perseel in jou eie woorde','Describe your electricity problem, equipment and priorities':'Beskryf jou elektrisiteitsprobleem, toerusting en prioriteite','Start voice capture':'Begin stemopname','Listening… tap to stop':'Luister… tik om te stop','Use these notes':'Gebruik hierdie notas',
    'Energy':'Energie','Site':'Perseel','Solution':'Oplossing','Finance':'Finansiering','Snapshot':'Oorsig','Guided mode':'Begeleide modus','Advanced mode':'Gevorderde modus','Advanced':'Gevorderd','We will keep this simple and make transparent assumptions.':'Ons hou dit eenvoudig en wys alle aannames duidelik.','Fine-tune technical and financial assumptions.':'Verfyn tegniese en finansiële aannames.',
    'Let’s understand your energy spend':'Kom ons verstaan jou energiebesteding','Use the number you know. You can skip anything else.':'Gebruik die syfer wat jy ken. Jy kan die res oorslaan.','I know my monthly bill':'Ek ken my maandelikse rekening','I know my monthly kWh':'Ek ken my maandelikse kWh','Upload a bill':'Laai ’n rekening op','Average monthly bill':'Gemiddelde maandelikse rekening','including VAT':'BTW ingesluit','Average monthly usage':'Gemiddelde maandelikse verbruik','How much billing history do you have?':'Hoeveel rekeninggeskiedenis het jy?','One recent bill':'Een onlangse rekening','About 3 months':'Ongeveer 3 maande','About 6 months':'Ongeveer 6 maande','12 months or more':'12 maande of meer','Drop bills or meter data here':'Plaas rekeninge of meterdata hier','PDF, photo, CSV or spreadsheet':'PDF, foto, CSV of sigblad','What kind of operation is this?':'Watter soort onderneming is dit?','Farm / Agriculture':'Plaas / Landbou','Factory / Industrial':'Fabriek / Industrieel','Commercial / Retail':'Kommersieel / Kleinhandel','Hospitality':'Gasvryheid','Mining / Quarry':'Mynbou / Steengroef','Something else':'Iets anders','Advanced electricity details':'Gevorderde elektrisiteitsbesonderhede','Blended tariff':'Saamgestelde tarief','Recorded peak demand':'Aangetekende piekaanvraag','Demand charge':'Aanvraagheffing','Continue to site →':'Gaan voort na perseel →',
    'Tell us about your site':'Vertel ons van jou perseel','We use location and operating patterns to tighten the estimate.':'Ons gebruik ligging en bedryfspatrone om die raming te verfyn.','Where is the site?':'Waar is die perseel?','Search':'Soek','or':'of','◎ Use my current location':'◎ Gebruik my huidige ligging','You can also choose a province below.':'Jy kan ook ’n provinsie hieronder kies.','Province':'Provinsie','Choose province':'Kies provinsie','Electricity supply':'Elektrisiteitsvoorsiening','Eskom direct':'Eskom direk','Municipality':'Munisipaliteit','Private / landlord':'Privaat / verhuurder','Not sure':'Nie seker nie','When do you use most electricity?':'Wanneer gebruik jy die meeste elektrisiteit?','Mostly daytime':'Meestal bedags','More than 60% while the sun is up':'Meer as 60% gedurende daglig','Day and night':'Dag en nag','A fairly even operating pattern':'’n Redelik gelyke bedryfspatroon','Mostly at night':'Meestal snags','Less than 30% during daytime':'Minder as 30% bedags','What do you want to power?':'Wat wil jy van krag voorsien?','Choose everything that applies':'Kies alles wat van toepassing is','＋ Add custom equipment':'＋ Voeg eie toerusting by','Nothing selected yet. We can estimate from your bill if you prefer.':'Niks is nog gekies nie. Ons kan vanaf jou rekening raam.','Advanced site details':'Gevorderde perseelbesonderhede','Usable roof area':'Bruikbare dakoppervlakte','Usable ground area':'Bruikbare grondoppervlakte','Planned load growth':'Beplande lasgroei','← Back':'← Terug','Build my options →':'Bou my opsies →',
    'Build the right energy strategy':'Bou die regte energiestrategie','Start with the outcome you need. Add or remove options at any time.':'Begin met die uitkoms wat jy nodig het. Voeg opsies enige tyd by of verwyder dit.','What matters most right now?':'Wat is nou die belangrikste?','Protect cash flow':'Beskerm kontantvloei','Low or no upfront capital':'Min of geen aanvangskapitaal','Own the system':'Besit die stelsel','Build a long-term asset':'Bou ’n langtermynbate','Fastest return':'Vinnigste opbrengs','Maximise financial benefit':'Maksimeer finansiële voordeel','How much continuity do you need?':'Hoeveel kontinuïteit benodig jy?','Cost saving':'Kostebesparing','No battery required':'Geen battery nodig nie','Critical loads':'Kritieke laste','Keep essentials operating':'Hou noodsaaklike toerusting aan die gang','Full-site resilience':'Volledige perseelweerbaarheid','Extended operational continuity':'Verlengde bedryfskontinuïteit','Optional upgrades':'Opsionele opgraderings','See the impact instantly':'Sien die impak onmiddellik','Battery storage':'Batteryberging','Generator integration':'Kragopwekker-integrasie','Energy management':'Energiebestuur','Power-factor correction':'Drywingsfaktorkorreksie','Solar carports':'Sonkragmotorafdakke','Ground-mount array':'Grondgemonteerde stelsel','EV charging ready':'Gereed vir EV-laai','Export control':'Uitvoerbeheer','Roof reinforcement allowance':'Voorsiening vir dakversterking','Extended warranty':'Verlengde waarborg','Grid application support':'Netwerkaansoekondersteuning','Performance & O&M plan':'Prestasie- en O&M-plan','Advanced operating details':'Gevorderde bedryfsbesonderhede','Monthly diesel spend':'Maandelikse dieselbesteding','Typical outage duration':'Tipiese onderbrekingsduur','Critical portion of load':'Kritieke deel van las','Performance ratio':'Prestasie-verhouding','Annual PV degradation':'Jaarlikse PV-degradasie','Existing generator':'Bestaande kragopwekker','None':'Geen','Manual generator':'Handkragopwekker','Automatic generator / ATS':'Outomatiese kragopwekker / ATS','Compare finance →':'Vergelyk finansiering →',
    'Compare ways to fund it':'Vergelyk maniere om dit te finansier','See the estimated cash impact—not just the system price.':'Sien die geraamde kontantimpak—nie net die stelselprys nie.','Indicative project':'Aanduidende projek','Year-one benefit':'Jaar-een-voordeel','Recommended route':'Aanbevole roete','Outright purchase':'Kontantaankoop','Own from day one':'Besit vanaf dag een','Bank finance':'Bankfinansiering','Deposit plus fixed loan':'Deposito plus vaste lening','Rent-to-own':'Huur om te besit','No or low upfront capital':'Geen of lae aanvangskapitaal','Energy services / PPA':'Energiedienste / PPA','Pay for delivered energy':'Betaal vir gelewerde energie','Adjust finance assumptions':'Pas finansiële aannames aan','Bank interest':'Bankrente','Loan term':'Leningstermyn','Deposit':'Deposito','PPA escalation':'PPA-eskalasie','Grid escalation':'Netwerkeskalasie','Discount rate':'Diskontokoers','PPA starting discount':'PPA-aanvangsafslag','PPA starting tariff':'PPA-aanvangstarief','Analysis period':'Ontledingstydperk','Indicative company tax rate':'Aanduidende maatskappybelastingkoers','View my snapshot →':'Bekyk my oorsig →',
    'YOUR PRE-FEASIBILITY SNAPSHOT':'JOU VOORAF-HAALBAARHEIDSOORSIG','A clearer energy path starts here.':'’n Duideliker energiepad begin hier.','data confidence':'datavertroue','RECOMMENDED FIRST ROUTE':'AANBEVOLE EERSTE ROETE','20-YEAR CAPITAL DECISION':'20-JAAR-KAPITAALBESLUIT','What each route could cost':'Wat elke roete kan kos','Base':'Basis','Conservative':'Konserwatief','Upside':'Optimisties','ENERGY MATCH':'ENERGIEPASSING','Typical operating day':'Tipiese bedryfsdag','SOLUTION':'OPLOSSING','Proposed first configuration':'Voorgestelde eerste konfigurasie','MONTHLY ENERGY':'MAANDELIKSE ENERGIE','Consumption and solar generation through the year':'Verbruik en sonkragopwekking deur die jaar','YEAR-ONE CASH FLOW':'JAAR-EEN-KONTANTVLOEI','Where the value comes from':'Waar die waarde vandaan kom','ENERGY FLOW':'ENERGIEVLOEI','How energy moves through the site':'Hoe energie deur die perseel vloei','SENSITIVITY':'SENSITIWITEIT','How tariff and production changes affect value':'Hoe tarief- en produksieveranderings waarde beïnvloed','FINANCE COMPARISON':'FINANSIERINGSVERGELYKING','Decision table':'Besluittabel','READINESS':'GEREEDHEID','What we know':'Wat ons weet','NEXT REVIEW':'VOLGENDE OORSIG','What could change this result':'Wat hierdie resultaat kan verander','Anything Chariot should know?':'Enigiets wat Chariot moet weet?','NEXT STEP':'VOLGENDE STAP','Turn this estimate into an investment-ready assessment.':'Verander hierdie raming in ’n beleggingsgereed assessering.','Schedule an energy review →':'Skeduleer ’n energie-oorsig →','Share with Chariot on WhatsApp':'Deel met Chariot op WhatsApp','Send by email':'Stuur per e-pos','Download / print report':'Laai verslag af / druk','← Review assumptions':'← Hersien aannames','Refine my assessment':'Verfyn my assessering',
    'LIVE INDICATIVE VIEW':'REGSTREEKSE AANDUIDENDE OORSIG','Your energy opportunity':'Jou energiegeleentheid','System range':'Stelselreeks','Estimated capex':'Geraamde kapitaaluitgawe','Cash-flow route':'Kontantvloei-roete','20-YEAR COST OUTLOOK':'20-JAAR-KOSTEVOORUITSIG','Now':'Nou','Data confidence':'Datavertroue','Starting':'Begin','Add your monthly bill to begin.':'Voeg jou maandelikse rekening by om te begin.','supplied':'verskaf','Assumptions visible':'Aannames sigbaar','WE’RE HERE TO HELP':'ONS IS HIER OM TE HELP','You do not need to know the technical answers.':'Jy hoef nie die tegniese antwoorde te ken nie.','Open WhatsApp':'Open WhatsApp','BOOK AN ENERGY REVIEW':'BESPREEK ’N ENERGIE-OORSIG','Choose a convenient starting point.':'Kies ’n gerieflike beginpunt.','Your name':'Jou naam','Full name':'Volle naam','Company':'Maatskappy','Company or site':'Maatskappy of perseel','Phone or email':'Telefoon of e-pos','How should we reach you?':'Hoe moet ons jou kontak?','Preferred time':'Voorkeurtyd','Weekday morning':'Weeksoggend','Weekday afternoon':'Weeksmiddag','As soon as possible':'So gou moontlik','Send meeting request →':'Stuur vergaderingversoek →','Monthly bill':'Maandelikse rekening','Indicative solar':'Aanduidende sonkrag','Battery allowance':'Batteryvoorsiening','Not included':'Nie ingesluit nie','Indicative capex':'Aanduidende kapitaaluitgawe','Recommended first route':'Aanbevole eerste roete','Client notes':'Kliëntnotas','Not specified':'Nie gespesifiseer nie','Location to confirm':'Ligging moet bevestig word','None supplied':'Niks verskaf nie','Please add your name and phone or email.':'Voeg asseblief jou naam en telefoon of e-pos by.','Chariot Energy Review Request':'Chariot Energie-oorsigversoek','Name':'Naam','Company/site':'Maatskappy/perseel','Not supplied':'Nie verskaf nie','Contact':'Kontak','Clear this assessment and start again?':'Vee hierdie assessering uit en begin weer?','Indicative pre-feasibility only. Please contact me to validate the assessment.':'Slegs ’n aanduidende vooraf-haalbaarheid. Kontak my om die assessering te bekragtig.'
  };

  const dictionaries={zu,af};
  const originals=new WeakMap();
  let lang=localStorage.getItem('chariot_language')||'en';
  let observer;

  function translateText(value,target=lang){
    if(!value||target==='en'||!dictionaries[target])return value;
    const lead=(value.match(/^\s*/)||[''])[0],trail=(value.match(/\s*$/)||[''])[0],core=value.trim();
    if(!core)return value;
    const dict=dictionaries[target];
    if(dict[core])return lead+dict[core]+trail;
    let out=core;
    Object.keys(dict).filter(k=>k.length>5&&out.includes(k)).sort((a,b)=>b.length-a.length).forEach(k=>{out=out.split(k).join(dict[k])});
    if(target==='zu')out=out.replace(/Typical (\d[\d.]*) kW · editable/g,'Okuvamile $1 kW · kuyalungiseka').replace(/(\d+) key assumptions/g,'izilinganiso ezibalulekile ezi-$1').replace(/(\d+) load groups? selected/g,'amaqembu okusetshenziswa akhethiwe: $1');
    if(target==='af')out=out.replace(/Typical (\d[\d.]*) kW · editable/g,'Tipies $1 kW · wysigbaar').replace(/(\d+) key assumptions/g,'$1 sleutelaannames').replace(/(\d+) load groups? selected/g,'$1 lasgroepe gekies');
    return lead+out+trail;
  }

  function translateNode(node){
    if(node.nodeType===Node.TEXT_NODE){
      if(!node.parentElement||/^(SCRIPT|STYLE|NOSCRIPT)$/.test(node.parentElement.tagName))return;
      if(!originals.has(node))originals.set(node,node.nodeValue);
      node.nodeValue=lang==='en'?originals.get(node):translateText(originals.get(node),lang);
      return;
    }
    if(node.nodeType!==Node.ELEMENT_NODE)return;
    ['placeholder','title','aria-label'].forEach(attr=>{
      if(!node.hasAttribute(attr))return;
      const key='i18nOriginal'+attr.replace(/-([a-z])/g,(_,c)=>c.toUpperCase()).replace(/^./,c=>c.toUpperCase());
      if(!node.dataset[key])node.dataset[key]=node.getAttribute(attr);
      node.setAttribute(attr,lang==='en'?node.dataset[key]:translateText(node.dataset[key],lang));
    });
  }

  function scanSubtree(root){
    translateNode(root);
    root.querySelectorAll&&root.querySelectorAll('*').forEach(translateNode);
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode()))translateNode(n);
  }

  function scan(root=document.body){
    if(observer)observer.disconnect();
    scanSubtree(root);
    if(observer)observer.observe(document.body,{childList:true,subtree:true,characterData:true});
  }

  function setLanguage(next){
    lang=LANGS[next]?next:'en';
    localStorage.setItem('chariot_language',lang);
    document.documentElement.lang=LANGS[lang].locale;
    const select=document.getElementById('languageSelect');if(select)select.value=lang;
    scan();
    document.dispatchEvent(new CustomEvent('chariot:languagechange',{detail:{language:lang}}));
  }

  function init(){
    observer=new MutationObserver(mutations=>{
      observer.disconnect();
      mutations.forEach(m=>{
        if(m.type==='characterData')translateNode(m.target);
        m.addedNodes&&m.addedNodes.forEach(node=>scanSubtree(node));
      });
      observer.observe(document.body,{childList:true,subtree:true,characterData:true});
    });
    const select=document.getElementById('languageSelect');if(select)select.addEventListener('change',e=>setLanguage(e.target.value));
    setLanguage(lang);
  }

  window.ChariotI18n={t:(s)=>translateText(s,lang),translateText,setLanguage,getLanguage:()=>lang,speechLang:()=>LANGS[lang].speech,locale:()=>LANGS[lang].locale};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
